name: reuse Push

on:
  workflow_call:
    inputs:
      commits:
        type: string
        required: true
      run:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: push
        run: |
          ${{inputs.run}}
          git config --global user.name "Sleepingoff"   
          git config --global user.email "justjh30@gmail.com"
          git add .
          git commit -m ${{inputs.commits}}
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
